apiVersion: job-scheduling-operator.openinnovation.ai/v1
kind: ComputeJob
metadata:
  labels:
    app.kubernetes.io/name: job-scheduling-operator
    app.kubernetes.io/managed-by: kustomize
  name: computejob-sample-failed
spec:
  command: ["perlo",  "-Mbignum=bpi", "-wlex", "print bpi(2000)"]
  parallelism: 1
